QBIT_CONF = r"""
[AutoRun]
OnTorrentAdded\Enabled=false
OnTorrentAdded\Program=
enabled=false
program=

[BitTorrent]
Session\AddExtensionToIncompleteFiles=true
Session\AddTrackersEnabled=true
Session\AdditionalTrackers={trackers_url}
Session\AlternativeGlobalDLSpeedLimit=0
Session\AlternativeGlobalUPSpeedLimit=0
Session\AnnounceToAllTrackers=true
Session\AnonymousModeEnabled=false
Session\AsyncIOThreadsCount=16
Session\DHTEnabled=true
Session\DefaultSavePath=/usr/src/app/downloads/
Session\DiskCacheSize=-1
Session\ExcludedFileNames=
Session\GlobalMaxRatio=0
Session\GlobalMaxSeedingMinutes=-1
Session\IgnoreLimitsOnLAN=true
Session\IgnoreSlowTorrentsForQueueing=true
Session\LSDEnabled=true
Session\MaxActiveDownloads=100
Session\MaxActiveTorrents=50
Session\MaxActiveUploads=50
Session\MaxConnections=-1
Session\MaxConnectionsPerTorrent=-1
Session\MaxRatioAction=0
Session\MaxUploads=-1
Session\MaxUploadsPerTorrent=-1
Session\MultiConnectionsPerIp=true
Session\PeXEnabled=true
Session\Port=6336
Session\Preallocation=true
Session\QueueingSystemEnabled=false
Session\SlowTorrentsDownloadRate=2
Session\SlowTorrentsInactivityTimer=600
Session\SlowTorrentsUploadRate=2
Session\TempPath=/usr/src/app/downloads/incomplete/
Session\TempPathEnabled=true
Session\uTPRateLimited=false

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=4

[Network]
Proxy\OnlyForTorrents=false

[Preferences]
Advanced\AnnounceToAllTrackers=true
Advanced\AnonymousMode=false
Advanced\IgnoreLimitsLAN=false
Advanced\LtTrackerExchange=true
Advanced\RecheckOnCompletion=false
Advanced\trackerPort=9000
Advanced\trackerPortForwarding=false
Bittorrent\AddTrackers=false
Bittorrent\DHT=true
Bittorrent\LSD=true
Bittorrent\MaxConnecs=-1
Bittorrent\MaxConnecsPerTorrent=-1
Bittorrent\MaxRatio=-1
Bittorrent\MaxRatioAction=0
Bittorrent\MaxUploads=-1
Bittorrent\MaxUploadsPerTorrent=-1
Bittorrent\PeX=true
Connection\ResolvePeerCountries=true
Downloads\DiskWriteCacheSize=-1
Downloads\PreAllocation=true
Downloads\SavePath=/usr/src/app/downloads/
Downloads\TempPath=/usr/src/app/downloads/incomplete/
Downloads\UseIncompleteExtension=true
DynDNS\DomainName=changeme.dyndns.org
DynDNS\Enabled=false
DynDNS\Password=
DynDNS\Service=DynDNS
DynDNS\Username=
General\Locale=
General\PreventFromSuspendWhenDownloading=true
MailNotification\email=
MailNotification\enabled=false
MailNotification\password=adminadmin
MailNotification\req_auth=true
MailNotification\req_ssl=false
MailNotification\sender=qBittorrent_notification@example.com
MailNotification\smtp_server=smtp.changeme.com
MailNotification\username=admin
Queueing\IgnoreSlowTorrents=true
Queueing\MaxActiveDownloads=100
Queueing\MaxActiveTorrents=50
Queueing\MaxActiveUploads=50
Queueing\QueueingEnabled=false
Search\SearchEnabled=true
WebUI\Address=*
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\BanDuration=3600
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\CustomHTTPHeaders=
WebUI\CustomHTTPHeadersEnabled=false
WebUI\Enabled=true
WebUI\HTTPS\CertificatePath=
WebUI\HTTPS\Enabled=false
WebUI\HTTPS\KeyPath=
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=true
WebUI\MaxAuthenticationFailCount=5
WebUI\Port=8090
WebUI\ReverseProxySupportEnabled=false
WebUI\RootFolder=
WebUI\SecureCookie=true
WebUI\ServerDomains=*
WebUI\SessionTimeout=3600
WebUI\TrustedReverseProxiesList=
WebUI\UseUPnP=false
WebUI\Username=admin
"""
